(function() {var implementors = {};
implementors['ucl'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='libucl_sys/enum.ucl_type_t.html' title='libucl_sys::ucl_type_t'>ucl_type_t</a>&gt; for <a class='enum' href='ucl/object/types/enum.Type.html' title='ucl::object::types::Type'>Type</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.i64.html'>i64</a>&gt; for <a class='struct' href='ucl/object/builder/struct.Builder.html' title='ucl::object::builder::Builder'>Builder</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.f64.html'>f64</a>&gt; for <a class='struct' href='ucl/object/builder/struct.Builder.html' title='ucl::object::builder::Builder'>Builder</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.bool.html'>bool</a>&gt; for <a class='struct' href='ucl/object/builder/struct.Builder.html' title='ucl::object::builder::Builder'>Builder</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/collections/string/struct.String.html' title='collections::string::String'>String</a>&gt; for <a class='struct' href='ucl/object/builder/struct.Builder.html' title='ucl::object::builder::Builder'>Builder</a>","impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;&amp;'a <a href='http://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>&gt; for <a class='struct' href='ucl/object/builder/struct.Builder.html' title='ucl::object::builder::Builder'>Builder</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='libucl_sys/enum.ucl_emitter.html' title='libucl_sys::ucl_emitter'>ucl_emitter</a>&gt; for <a class='enum' href='ucl/object/emitter/enum.Emitter.html' title='ucl::object::emitter::Emitter'>Emitter</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
